version: '3'
volumes:
    dbdata: ~
services:
    php:
        build: .
        hostname: wkhtml2pdf
        volumes:
         - ./app:/app
        ports:
         - 9090:80
        environment:
         - APP_ENV=dev
         - CONTAINER_ENV=dev
